{{- if .Values.configMap.enabled -}}
{{- if or .Values.configMap.data .Values.configMap.files -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "app.configMapName" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
  {{- with .Values.configMap.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- range $key, $value := .Values.configMap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- range $key, $value := .Values.configMap.files }}
  {{ $key }}: |
    {{- tpl $value $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
